---
- name: Install Unofficial Syslog-NG RPM Repository
  yum_repository:
    name: syslog-ng
    description: COPR Build Service Syslog-NG Repo
    baseurl: https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng319/repo/epel-7/czanik-syslog-ng319-epel-7.repo

- name: Install Syslog-NG
  become: true 
  yum:
    name: syslog-ng
    state: present
  notify: restart syslog-ng

